### ISSUE TITLE
Android 5 Lollipop VPN fails

### ISSUE THREAD

**Issue by midi** [leapcode/bitmask_android#157]
https://leap.se/code/issues/6232

Update: fixed by arne in the latest openvpn update: https://play.google.com/store/apps/details?id=de.blinkt.openvpn

Running LPX13D (latest 5 preview) on hammerhead (Nexus 5), rooted with chainfire's stock, selinux enforced kernel, with bitmask 0.7.0.

Connecting seems to work, however the connection fails with this error:
Unable to redirect default gateway -cannot read current default gateway from system.

Otherwise VPN support is much nicer on Lollipop. Sleeker VPN indication with just a key symbol next to the network indicators on the status bar and only one initial warning popup.

**Comment by cyBerta** [comment]
not reproducable on current master
