### ISSUE TITLE
This is not a trusted Bitmask provider

### ISSUE THREAD

**Issue by danialbehzadi** [leapcode/bitmask_android#164]
When I add my provider or even when I tap on Bitmask demo. A dialoge opens and tell me "This is not a trusted Bitmask provider" with two buttons "Cancel" and "Retry". And if I tap Retry button a new dialoge opens with no text and two "Cancel" and "Retry" buttons. After some teries, Bitmask will crash with android annouce "Bitmask has stopped" and two "OK" and "Report" buttons.
My device:
Nokia X2_DS, Android 4.3

**Comment by davinerd** [comment]
This can also means that you are using a self signed cert and you didn't install the cert on your android device. Please follow the steps below:
1 - Copy the .crt file to the root of the /sdcard folder inside your Android device
2 - Inside your Android device, Settings > Security > Install from storage. It should detect the certificate and let you add it to the device

**Comment by parmegv** [comment]
Thanks @davinerd, that's definitely a possibility.

@danialbehzadi  Any news on this bug?

**Comment by xeverse** [comment]
What would be the solution for black.riseup.net?

**Comment by elijh** [comment]
This has been fixed. Should be available in play store shortly.
