### ISSUE TITLE
Bitmask crashes after reboot or false start

### ISSUE THREAD

**Issue by bungabunga** [leapcode/bitmask_android#181]
From version 1.8.2 onward (maybe also 1.8.1 but that version always force closed for me) Bitmask very often crashes at boot. Sometimes it doesn't and sometimes it kind of fail-starts (see attached picture). If it crashes and I later start in normaly, then it starts and works fine.

Login credentials also disappear after reboot.

I wanted to post log but it seems that it doesn't make logs so early at system start.

![leap](https://cloud.githubusercontent.com/assets/2994878/5561080/240a6d70-8dbc-11e4-9155-49a6fe630b3d.png)

**Comment by gerroon** [comment]
I have the same issue. I installed it right after I clicked on riseup.net the first time it started crashing. I cant open it anymore

**Comment by bungabunga** [comment]
Seems fixed, at least on Lollipop.
