### ISSUE TITLE
Checkbox ("I trust this application") doesn't work after last update

### ISSUE THREAD

**Issue by mwehu** [leapcode/bitmask_android#189]
>OS: Android 4.4.4 (CM)
>Bitmask's update version: 0.9.2

I reinstalled the app, but the problem persists.

**Comment by parmegv** [comment]
Can you check it, and if so, does it have any effect?

**Comment by mwehu** [comment]
@parmegv, I can't check it. The check box remains unchecked, even after I touch her.

**Comment by mwehu** [comment]
@parmegv Solved after restarting the device. Thanks.
