### ISSUE TITLE
Distribute app through F-Droid

### ISSUE THREAD

**Issue by nexus-uw** [leapcode/bitmask_android#211]
It would be greatly appriated if this app could also be distributed through [F-Droid](https://f-droid.org/), a FOSS 'app store' for android. By distributing this app through F-Droid, it becomes discoverable (and kept up to date) for users who wish to avoid Google Play Services.

From what I have seen, bitmask meets all the critia outlined in their inclusion policy (https://f-droid.org/wiki/page/Inclusion_Policy), so it should be easily accepted.

**Comment by elijh** [comment]
thanks.

now tracking f-droid related issues here https://0xacab.org/leap/bitmask_android/issues/8743

**Comment by IzzySoft** [comment]
While it didn't arrive there: Would you consider publishing it on the `releases/` page? I could then automatically fetch it and put it into [my F-Droid compatible repo](https://android.izzysoft.de/repo), with updates usually available within 24h.

**Comment by IzzySoft** [comment]
@elijh Just refreshing my offer. Please let me know if you're interested. If not, I can take it off my watchlist, though I'd prefer a yes :smile_cat:

**Comment by aguestuser** [comment]
hi @IzzySoft -- thanks so much for the offer! we are very much interested! (and grateful!)

it will likely be at least a few days before we have a chance to publish a signed .apk to the `/releases` tree, but we are eager to do so and will ping you once we have.

apologies for the delay in getting back to you. i've been transitioning into maintaining the android code-base over the month or so and i've just now cleared out enough time to devote full attention to matters such as this. thanks for being patient, and for your kind offer. 

we're *very* excited about being able to distribute the app through f-droid. :dancer: :dancer: :dancer:

**Comment by aguestuser** [comment]
for future reference: we do most of our issue tracking on our self-hosted gitlab instance here: https://0xacab.org/leap/bitmask_android/

we'll respond to any discussion anywhere, but you are likely to get a more prompt reply by posting / commenting there.

cheers!

**Comment by IzzySoft** [comment]
Thanks, @aguestuser ! Looking foward to read from you again then. Whenever you update this issue I'll get a notification automatically.

Understood you focus your tracking at another place – but please understand I cannot watch everywhere :wink: So I'm thankful you also watch here – and content if it takes a little longer. Glad to offer you contribution via my repo. It's not the "official" one, but meanwhile the second largest, accepted by many, and easy to use via the F-Droid client.

**Comment by aguestuser** [comment]
I @IzzySoft haven't forgotten your kind offer! Have been pulled onto other things, but am turning attention back toward getting a signed apk published on our releases tree here shortly!

**Comment by IzzySoft** [comment]
@aguestuser thanks for the heads-up! I keep waiting patiently, as promised :smile_cat:

**Comment by cyBerta** [comment]
added to IzzySoft's repo. Official FDroid repo will come soon.

**Comment by varac** [comment]
F-Droid inclusion is tracked here:  https://0xacab.org/leap/bitmask_android/issues/8743

**Comment by IzzySoft** [comment]
@cyBerta careful. Remember the version in my repo is for testing ("beta channel"). Different package name. Stable one will be in the F-Droid main repo when ready. Be aware of the difference – but you should know that better than me – maybe both are identical except for the package name :wink:

**Comment by cyBerta** [comment]
Thanks for pointing it out! I've forgotten to say that.

**Comment by IzzySoft** [comment]
Thought so :grin: Shall I remind you again once the stables popping up at the official repo?

**Comment by cyBerta** [comment]
No thanks, the beta versions you're publishing have a suffix 'beta' in the package name, whereas the stable versions distributed through the official repository will have the normal package name. That's already arranged.

**Comment by IzzySoft** [comment]
@cyBerta your beta link (`https://dl.bitmask.net/client/android/Bitmask-Android-testing.apk`) currently returns the release package (without the `.beta` suffix in the package name). Shall I drop the beta from my repo, do you have a new URL, or is it just a mishap?

**Comment by cyBerta** [comment]
@IzzySoft  sorry, this was a mistake. I've fixed that yesterday. Thanks for telling us!

**Comment by IzzySoft** [comment]
@cyBerta Thanks! :+1: Confirmed: Auto-Update today no longer failed, new version is now available in my repo.
