### ISSUE TITLE
32-bit instead of 64-bit libopenvpn.so

### ISSUE THREAD

**Issue by the-solipsist** [leapcode/bitmask_android#213]
After opening Bitmask for Android, installed from the Google Play Store, I click "Turn On", and I get the following error:

```
P: CANNOT LINK EXECUTABLE DEPENDENCIES: "libopenvpn.so" is 32-bit instead of 64-bit.
Process exited with exit value 1.
```

I'm using a rooted ONE A20003 (Oneplus 2) with Android 5.1.1 (Oxygen 2.2.0) running
Build: ONE A2003_14_151211

Do let me know what other details would be helpful.

**Comment by parmegv** [comment]
Hi!

 Can you check if https://f-droid.org/repository/browse/?fdfilter=openvpn&fdid=de.blinkt.openvpn works? We build the libraries like them, but maybe we have changed something that breaks support for your architecture.

 Android should be picking the arm64-v8a library, which is included in our Application.mk (https://github.com/parmegv/ics-openvpn/blob/bitmask/main/jni/Application.mk#L1).

**Comment by the-solipsist** [comment]
Hi, OpenVPN for Android (Arne Schwabe / Blinkt.de) works for me (but I installed the one from the Play Store — though that shouldn't make a difference).  I'm using that with Riseup servers.  But Bitmask still doesn't.

**Comment by cyBerta** [comment]
We'll track that issue now there: https://0xacab.org/leap/bitmask_android/issues so I'm going to close it here in order to avoid duplicates. Thanks for reporting it and sorry for the delay!
