### ISSUE TITLE
connection dropping often

### ISSUE THREAD

**Issue by ghost** [leapcode/bitmask_android#214]
After only a few minutes I find myself looking at my statusbar wondering why the VPN icon has suddenly dissappeared.
The app keeps closing the VPN for some reason, or it gets killed by android. I'm not sure.
So basically I've been browsing the web assuming I was using a VPN :/

**Comment by hughjfchen** [comment]
I had the exactly same problem. I checked the log and found the app will fire an inactivity-time signal and then restart after a few mins the connection established. But actually I'had been watching a youtube movie so I don't know why such a signal would be fired. I can provide the log if any further info needed.

**Comment by parmegv** [comment]
@hughjfchen If you can provide a log, that would definitely be useful :)

Thanks

**Comment by cyBerta** [comment]
We track that issue now on our internal issue tracker so I'll close it here.
