### ISSUE TITLE
FC when turning on VPN

### ISSUE THREAD

**Issue by takiainen** [leapcode/bitmask_android#219]
Running latest bitmask 0.9.4 on SlimLP for Oneplus One. I'm able to login to rise up VPN, but when clicking "turn on" bitmask force closes.

Another question: is bitmask still being developed, noticed that your website's download page has latest version from June 2015?

**Comment by takiainen** [comment]
I noticed I had "vpn-dialogs" removed from my system. That's why VPN did not work. 

Now my bitmask works fine.

**Comment by parmegv** [comment]
thanks @takiainen for the report and the "fix".

Bitmask is in maintenance mode. I recently updated the underlying ics-openvpn codebase, but it is true that we did not publish a test apk anywhere.

Will try to do it this week, along with a couple of minor improvements.
