### ISSUE TITLE
Can't receive GCM push messges on Bitmask

### ISSUE THREAD

**Issue by bungabunga** [leapcode/bitmask_android#220]
I can't receive GCM push messages (Signal messenger, Threema messenger, Wire messenger...) for months although it once used to work without problems. I thought that it was a Lollipop limitation since it all started with upgrading my phone to Android 5.1. But then i discovered that people can receive GCM messages with other VPN clients on Lollipop. It also works on my phone if I use Orbot's new VPN feature. Only on Bitmask GCM push messages doesn't get through.

Also, Bitmask Android client was updated to the latest version approximately at the same time as I upgraded my phone to Lollipop, so maybe this is not a Lollipop limitation after all but a Bitmask bug.

Sony Xperia Z3c
Android 5.1
Bitmask for Android 0.9.4

**Comment by georgeowell** [comment]
I'm also having problems sending messages using Signal messenger rendering the VPN pretty much unusable. 

Cyanogen Mod 12.1 (Android 5.1)
Bitmask for Android 0.9.4

**Comment by cyBerta** [comment]
I'll move that issue to our internal bug tracker and close it here. Thanks for reporting it and sorry for the delay!
