### ISSUE TITLE
bitmask unusable

### ISSUE THREAD

**Issue by subproc** [leapcode/bitmask_android#223]
can't use bitmask 'cause can't connect to any provider...just demo.bitmask....i think need to update certificate for riseup...'cause they are getting out a new ca a few time ago

**Comment by jordila** [comment]
Having problems here too... ( Riseup user )
Then i tried http://black.riseup.net and VPN is working again

**Comment by jordila** [comment]
seems to be already fixed upon #227  or #225  ?

**Comment by cyBerta** [comment]
@jordila the attached image of your last comment shows the bitmask client for linux. I'll close that issue here as it seems not related to bitmask android. In addition to that I cannot reproduce that error. @subproc please leave a comment if you still have the same issue. And sorry for the delay!
