### ISSUE TITLE
security error

### ISSUE THREAD

**Issue by subproc** [leapcode/bitmask_android#224]
if i launch bitmask and choose riseup, it says me "security error,update the app or choose another provider" what i have to do? i'm on 0.9.5RC1

**Comment by elijh** [comment]
i think the was a temporary error with the riseup cert. try again.

**Comment by subproc** [comment]
i've tried many times, but with no success...i'm on marsmallow...same result with bitmask 0.9.2, 0.9.4, 0.9.5rc1...  
i can't import the riseup.pem 'cause in marshmallow can only be imported a psck file and not .pem...
calyx and demo.bitmask are working well, but riseup doesn't

**Comment by jordila** [comment]
Having problems here too... ( Riseup user )
Then i tried http://black.riseup.net and VPN is working again

peace, love and free software

**Comment by georgeowell** [comment]
I submitted a pull request to correct the URL but just saw someone reporting DNS leaks #226

**Comment by KwadroNaut** [comment]
The problem is the certificate pinning builtin. It's gotten worse due to LetsEncrypt integration, which implies more often these pins would need to change. https://leap.se/code/issues/8455

**Comment by KwadroNaut** [comment]
The problem is the certificate pinning builtin. It's gotten worse due to LetsEncrypt integration, which implies more often these pins would need to change. https://leap.se/code/issues/8455

**Comment by elijh** [comment]
This is resolved, will be available in the play store soon.
