### ISSUE TITLE
url pointing to Riseup's VPN  error ?

### ISSUE THREAD

**Issue by jordila** [leapcode/bitmask_android#225]
as mentioned in #224 
Having problems here ... ( Riseup user ) due to wrong http://riseup.net pointer ?

Then i tried http://black.riseup.net and VPN is working again

peace, love and free software

**Comment by subproc** [comment]
trying https://black.riseup.net and it work....but if i try dnsleaks test it leaks my dns resolver

**Comment by georgeowell** [comment]
Had to switch to the address above. It's vital this is patched!! People are relying on it in some cases for their safety.

**Comment by georgeowell** [comment]
I made #227 but won't have time to test it right now. We need to also investigate the DNS leaks.

**Comment by elijh** [comment]
I fixed the bug with riseup.net. now it should work normally again.

**Comment by georgeowell** [comment]
I'm still getting errors on this issue. Now even the black.riseup.net workaround isn't working.
