### ISSUE TITLE
dns leaks

### ISSUE THREAD

**Issue by subproc** [leapcode/bitmask_android#226]
because https://riseup.net it's not working, i'm using https://black.riseup.net, but bitmask leaks my real dns resolver

**Comment by subproc** [comment]
i'm on marshmallows with bitmask 0.9.5 rc1

**Comment by cyBerta** [comment]
we'll double check that and track the issue on https://0xacab.org/leap/bitmask_android/issues. I'll close it here to avoid duplicates.
