### ISSUE TITLE
Always-on VPN

### ISSUE THREAD

**Issue by ghost** [leapcode/bitmask_android#229]
Android 7.0+ can enforce the use of a VPN using an always-on VPN profile for VPN apps. (not just PPTP etc)
Under settings-->Wireless&NEtworks-->more-->VPN bitmask is listed as a VPN profile. When going into its settings Always-on VPN is grayed out saying "not supported by this app".
It'd be useful if bitmask supported this since it'd allow the system itself to prevent any outgoing connections in the clear (especially during boot)

**Comment by elijh** [comment]
Thanks for the heads up!

Lets have future discussion about this over at https://0xacab.org/leap/bitmask_android/issues/8742, where it is more likely to get acted on.
