### ISSUE TITLE
Can't connect to Riseup Black

### ISSUE THREAD

**Issue by pahapoika** [leapcode/bitmask_android#230]
Hey!
When i try to connect to Riseup Black using the Android app i get 
![screenshot_20170227-134403](https://cloud.githubusercontent.com/assets/15216654/23360430/e2b99b6c-fcf3-11e6-8da3-d7cda4254f69.png)

**Comment by pahapoika** [comment]
I'm pretty sure that the CA is outdated

**Comment by xybydy** [comment]
I have the same issue.

**Comment by just1602** [comment]
Have you just upgrade to android 7+?

**Comment by xybydy** [comment]
I'd been using nougat since it was available and bitmask worked well until I rooted my device and installed custom nougat rom. Now I'm getting the error above.

**Comment by just1602** [comment]
As far as I know, there is a bug with the android 7+, so if your custom rom is base on it, you'll probably get this error.

**Comment by xybydy** [comment]
Weird. I was having no issues on official build rom and my custom rom based on the exact same official build number. The rom only has UI tweaks. So I'm +1 to pahapoika, it might be the outdated CA certificate.

**Comment by pahapoika** [comment]
There's logcat: https://hastebin.com/avudititel.sql

**Comment by cyBerta** [comment]
We're trying to fix that bug at the moment. You can track that issue on our internal issue tracker here: 
https://0xacab.org/leap/bitmask_android/issues/8757.
