### ISSUE TITLE
Found a fresh 🐛 

### ISSUE THREAD

**Issue by jmfgdev** [leapcode/bitmask_android#231]
If I go to the demo provider, choose use as anon and and proceed to hit the login button above the turn on button, I can move the position of the button over, a few spots, then when I hit multitasking I can bug it even further. Making the button Blank out to grayish white and become unusable. This is on the latest stable.

**Comment by cyBerta** [comment]
hi @jmfgdev sorry for the delay!! We're currently starting the development for the bitmask android client again and will try to fix all reported bugs. Could you specify which device and android version you got? I cannot reproduce that described behavior with Lineage OS 14 (Android 7.1.2) on my s4 mini but maybe I didn't understand exactly your description. What did you mean by hit "multitasking"?

**Comment by jmfgdev** [comment]
I don't remember which device I was testing with at the time I posted the bug, but in answer to your question about multitasking, I mean the software key which activates the multitasking interface allowing the user to clear loaded apps to clear up RAM etc.

**Comment by cyBerta** [comment]
hey @jmfgdev thanks for the clarification. I've tried several emulators running API 16-25 and wasn't able to reproduce that behavior. I'll close that ticket for now. 
Please leave a comment if you experience the same bug and can provide more information about the device and the Android version.
