### ISSUE TITLE
VPN Reconnect sometimes hangs

### ISSUE THREAD

**Issue by bneg** [leapcode/bitmask_android#56]
**Logging progress in this issue:**
The problem as described is that sometimes when losing a network connection, or switching networks while LEAP is connected, the VPN reconnect will hang.  

**Objective:**
Gather more information on the nature of this bug, with log files and hopefully a repeatable repro

**Comment by cyBerta** [comment]
This issue will be tracked here: https://0xacab.org/leap/bitmask_android/issues/8767.
